#!/bin/bash
version="0-1-1"
alias_path="~/.config/zsheep/zsheep_app/"
#
cr="\e[1;31m"
cg="\e[1;32m"
cb="\e[1;34m"
r="\e[0m"
#
if ! grep -q "zsheep_${version}" ~/.zshrc
then
	echo "#" >> ~/.zshrc
	echo "# zsheep_${version} $(uname -s) $(date)" >> ~/.zshrc # sa uninstall
	echo "# zsheep alias list" >> ~/.zshrc
	echo 'alias gps="~/.config/zsheep/zsheep_app/42gps/gps"' >> ~/.zshrc
	echo 'alias sna="~/.config/zsheep/zsheep_app/snails/snails.sh"' >> ~/.zshrc
	echo 'alias snails="~/.config/zsheep/zsheep_app/snails/snails.sh"' >> ~/.zshrc
	echo 'alias sky="~/.config/zsheep/zsheep_app/askyy/askyy_road"' >> ~/.zshrc
	echo 'alias askyy="~/.config/zsheep/zsheep_app/askyy/askyy_road"' >> ~/.zshrc
	echo "# zsheep_@kodpe" >> ~/.zshrc # se unistall
	#
	if [ -d "${HOME}/.config" ]
	then
		mkdir ~/.config/zsheep
	else
		mkdir ~/.config
		mkdir ~/.config/zsheep
	fi
	cp -rf zsheep_app ~/.config/zsheep
	cp -f LICENSE ~/.config/zsheep
	echo -e "${cg}(>o.o>) zsheep installed${r}"
	echo -e "${cg}(>o.o>) Open a new terminal to use zsheep${r}"
else
	echo -e "${cb}(>o.o>) zsheep already installed${r}"
fi
# display zsheep manual
esc=" "
echo -e "${cb}(>o.o>) zsheep manual${r}"
echo
echo -e "${esc}$ ${cb}gps${r} e2r8p9"
echo -e "${esc}  Find your correction at 42Paris"
echo
echo -e "${esc}$ ${cb}sna${r} or ${cb}snails${r}"
echo -e "${esc}  Do snails run"
echo
echo -e "${esc}$ ${cb}sky${r} or ${cb}askyy${r}"
echo -e "${esc}  Start askyy the random night landscape"
echo
echo -e "${cb}-----------------------------------${r}"
#
exit
